In [30]:
# 라이브러리 로딩
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.display import display, HTML

sns.set()

display(HTML("<style>.container { width:100% !important; }</style>"))
#display(HTML(' <span style="color:red">the title is: <h1>Hello, world!</h1> </span>  '))

## 각 컬럼 width 최대로
pd.set_option('display.max_colwidth', -1)

# Use 3 decimal places in output display ex) {:,.0f}
pd.options.display.float_format = '{:,.0f}'.format

# Don't wrap repr(DataFrame) across additional lines
pd.set_option("display.expand_frame_repr", True)

# Set max rows displayed in output to 25
pd.set_option("display.max_rows", 60)

In [10]:
# 데이터파일 정의
use_colidx = np.arange(3,114)
use_colnms = ['매출귀속부서','영업대표','PJT코드','PJT명','End_User','매출처','구분','확률','시작일','종료일','수주금액','외주원가','상품원가','경비','GP1',
                '취급액_1','매출_1','용역수익_1','상품매출_1','외주원가_1','상품원가_1','경비_1','GP1_1',
                '취급액_2','매출_2','용역수익_2','상품매출_2','외주원가_2','상품원가_2','경비_2','GP1_2',
                '취급액_3','매출_3','용역수익_3','상품매출_3','외주원가_3','상품원가_3','경비_3','GP1_3',
                '취급액_4','매출_4','용역수익_4','상품매출_4','외주원가_4','상품원가_4','경비_4','GP1_4',
                '취급액_5','매출_5','용역수익_5','상품매출_5','외주원가_5','상품원가_5','경비_5','GP1_5',
                '취급액_6','매출_6','용역수익_6','상품매출_6','외주원가_6','상품원가_6','경비_6','GP1_6',
                '취급액_7','매출_7','용역수익_7','상품매출_7','외주원가_7','상품원가_7','경비_7','GP1_7',
                '취급액_8','매출_8','용역수익_8','상품매출_8','외주원가_8','상품원가_8','경비_8','GP1_8',
                '취급액_9','매출_9','용역수익_9','상품매출_9','외주원가_9','상품원가_9','경비_9','GP1_9',
                '취급액_10','매출_10','용역수익_10','상품매출_10','외주원가_10','상품원가_10','경비_10','GP1_10',
                '취급액_11','매출_11','용역수익_11','상품매출_11','외주원가_11','상품원가_11','경비_11','GP1_11',
                '취급액_12','매출_12','용역수익_12','상품매출_12','외주원가_12','상품원가_12','경비_12','GP1_12']
col_type = {"매출귀속부서":str,"영업대표":str,"PJT명":str,"End_User":str,"매출처":str,"구분":str,"시작일":str,"종료일":str}

csv_prev = 'D:\\MyPython\\boss_forecast\\boss_forecast_202001_v1.csv'
csv_this = 'D:\\MyPython\\boss_forecast\\boss_forecast_202001_v2.csv'

result_filepath = 'D:\\MyPython\\boss_forecast\\'

In [22]:
# 데이터파일 가져오기
boss_prev = pd.read_csv(csv_prev,header=1, usecols=use_colidx, names=use_colnms, index_col=2, thousands=',', decimal ='.', encoding='euc-kr', skipfooter = 2, engine = 'python', dtype=col_type)
boss_prev['집계'] ='전기'
boss_prev.set_index('집계', append=True)
boss_this = pd.read_csv(csv_this,header=1, usecols=use_colidx, names=use_colnms, index_col=2, thousands=',', decimal ='.', encoding='euc-kr', skipfooter = 2, engine = 'python', dtype=col_type)
boss_this['집계'] ='당기'
boss_this.set_index('집계', append=True)
boss_sales = pd.concat([boss_prev,boss_this])
boss_sales
df_outer = pd.merge(boss_prev, boss_this, on='PJT코드', how='outer')
df_outer.describe()
#df_outer.to_csv(result_filepath + 'boss_all.csv', encoding='euc-kr')

,확률_x,수주금액_x,외주원가_x,상품원가_x,경비_x,GP1_x,취급액_1_x,매출_1_x,용역수익_1_x,상품매출_1_x,...,경비_11_y,GP1_11_y,취급액_12_y,매출_12_y,용역수익_12_y,상품매출_12_y,외주원가_12_y,상품원가_12_y,경비_12_y,GP1_12_y
count,266,266,266,266,266,266,266,266,266,266,...,266,266,266,266,266,266,266,266,266,266
mean,84,"147,214,648","20,488,024","89,171,972","1,539,197","36,015,455",0,"10,822,980","3,244,989","7,577,992",...,"2,229","271,552",0,"6,965,602","195,729","6,769,874","69,558","6,523,673","2,270","370,101"
std,32,"276,889,919","102,470,495","143,471,001","8,291,193","88,149,180",0,"37,699,698","15,116,760","35,003,134",...,"18,476","1,793,564",0,"33,419,839","848,286","33,448,859","418,050","32,309,487","18,628","1,685,213"
min,0,0,0,0,0,"-114,000",0,"-1,380,960","-1,380,960",0,...,0,"-254,820",0,0,0,0,0,0,0,"-254,200"
25%,100,"12,655,350",0,0,0,"1,290,000",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50%,100,"60,000,000",0,"29,410,000",0,"6,112,500",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75%,100,"158,471,775",0,"119,469,640","72,000","19,597,052",0,"527,258",0,0,...,0,0,0,0,0,0,0,0,0,0
max,100,"3,000,000,000","1,100,000,000","1,200,000,000","121,500,000","800,000,000",0,"349,658,500","105,831,235","345,000,000",...,"254,820","24,547,500",0,"259,260,000","7,400,000","259,260,000","4,235,000","241,414,000","254,200","17,846,000"

In [23]:
# 확률변경건
boss_rate_ch = df_outer[df_outer['확률_x'] != df_outer['확률_y']]
boss_rate_ch.loc[:,['PJT명_x','확률_x','PJT명_y','확률_y']]

,PJT명_x,확률_x,PJT명_y,확률_y
PJT코드,,,,
2000071996,현대커머셜 '20년 SAS 라이선스 재계약,100,현대커머셜 '20년 SAS 라이선스 재계약,0
SA19065432,현대카드 '20년 HDP 재계약-4SKU,100,NaN,nan
SA19065143,현대카드 '20년 HDP 재계약-17SKU,100,NaN,nan
SA19065145,하나카드 '20년 HDP 재계약-5SKU,100,NaN,nan
SA19064835,하나은행 '20년 HDP 재계약-5SKU,100,NaN,nan
SA19063378,농협상호금융 SAS 라이선스 도입(EG),100,NaN,nan
SA20066950,농협은행 '20년 HDP 재계약-2SKU,100,NaN,nan
SA20066943,한국공항공사 클라우데라 라이선스 공급(8노드),75,NaN,nan
SA20067170,현대커머셜 클라우데라 라이선스 재계약(8노드),25,NaN,nan
SA19064715,현대캐피탈 클라우데라 라이선스 도입(29노드) 및 증설(10노드),25,NaN,nan
SA20067281,바이오스타랩 SAS 라이선스 재계약,100,NaN,nan
SA19065364,대림산업 Oracle EPM &재무전망 유지보수_2020,100,NaN,nan
SA19066293,한국신용정보원 SAS 라이선스 재계약,100,NaN,nan
SA19054833,삼성전자 VDMML 라이선스,25,삼성전자 VDMML 라이선스,10
SA19064214,CJ제일제당 빅데이터 플랫폼 구축,25,CJ제일제당 빅데이터 플랫폼 구축,75
SA19063832,아카데미 재계약(2020년1월)고려대학교 외 1건,100,NaN,nan
BNA19016,팬택씨앤아이 AWS 유지보수,0,팬택씨앤아이 AWS 유지보수,100
BNA19166,환국환경정책연구원 AWS 디파짓 계약,0,환국환경정책연구원 AWS 디파짓 계약,100
SA19064680,SAS 소프트웨어 재계약,100,NaN,nan
SA19065756,인천국제공항공사 빅데이터 라이선스 판매,50,NaN,nan
SA19062212,전사 빅데이터 플랫폼 구축사업,0,NaN,nan
SA20066873,CDH하둡 플랫폼 재계약,75,NaN,nan
SA20066830,호튼웍스 Subscription 도입,50,NaN,nan
SA20067180,CDH 하둡 플랫폼 재계약,100,NaN,nan
2000073220,NaN,nan,한국공항공사 클라우데라 라이선스 공급(8노드),100
2000073218,NaN,nan,하나은행 '20년 HDP 재계약-5SKU,100
2000073143,NaN,nan,농협은행 '20년 HDP 재계약-2SKU,100
2000073051,NaN,nan,하나카드 '20년 HDP 재계약-5SKU,100
SA20067818,NaN,nan,현대카드.캐피탈 클라우데라 신규 노드 도입(24노드),100
2000072860,NaN,nan,바이오스타랩 SAS 라이선스 재계약,100
BNA20031,NaN,nan,국도화학 연결시스템 유지보수_2020,100
BDA20003,NaN,nan,대림산업 Oracle EPM &재무전망 유지보수_2020,100
2000073024,NaN,nan,한국신용정보원 SAS 라이선스 재계약,100
SA20067746,NaN,nan,아난티 연결시스템 구축,0
BKA20008,NaN,nan,경영학과 2020년도 아카데미 재계약,100
BKA20006,NaN,nan,(사회의학교실)2020년도 아카데미 재계약,100
2000073094,NaN,nan,(교양학과) 2020년 아카데미 재계약,100
2000072984,NaN,nan,(서울행정) 아카데미 재계약,100
2000073097,NaN,nan,SAS 소프트웨어 재계약,100
SA20067586,NaN,nan,관세청 빅데이터플랫폼 구축,0
2000073062,NaN,nan,CDH 하둡 플랫폼 재계약,100
SA20067590,NaN,nan,DW Offloading을 위한 PoC 수행,25
SA20067644,NaN,nan,분석 플랫폼 시스템 구축 사업,0

In [24]:
# 확률변경건
boss_rate_ch = df_outer[df_outer['매출_1_x'] != df_outer['매출_1_y']]
boss_rate_ch.loc[:,['PJT명_x','확률_x','매출_1_x','PJT명_y','확률_y','매출_1_y']]

,PJT명_x,확률_x,매출_1_x,PJT명_y,확률_y,매출_1_y
PJT코드,,,,,,
BDA19140,신한AI 인프라 고도화 구축사업,100,"94,453,824",신한AI 인프라 고도화 구축사업 수행,100,0
BDA19140,신한AI 인프라 고도화 구축사업,100,"94,453,824",신한AI 인프라 고도화 구축사업 품질비용 내부이체(빅데이터사업팀 -> QA팀),100,0
BDA19140,신한AI 인프라 고도화 구축사업,100,"94,453,824",신한AI 인프라 고도화 구축사업 인건비 이체 (한수정 대리),100,0
2000071996,현대커머셜 '20년 SAS 라이선스 재계약,100,"40,479,000",현대커머셜 '20년 SAS 라이선스 재계약,0,0
SA19065432,현대카드 '20년 HDP 재계약-4SKU,100,0,NaN,nan,nan
SA19065143,현대카드 '20년 HDP 재계약-17SKU,100,0,NaN,nan,nan
SA19065145,하나카드 '20년 HDP 재계약-5SKU,100,"116,850,000",NaN,nan,nan
SA19064835,하나은행 '20년 HDP 재계약-5SKU,100,"135,840,000",NaN,nan,nan
SA19066494,이베이코리아 클라우데라 S/W 도입,100,"60,000,000",이베이코리아 클라우데라 S/W 도입,100,0
SA19063378,농협상호금융 SAS 라이선스 도입(EG),100,0,NaN,nan,nan
SA20066950,농협은행 '20년 HDP 재계약-2SKU,100,0,NaN,nan,nan
SA20066943,한국공항공사 클라우데라 라이선스 공급(8노드),75,"59,640,000",NaN,nan,nan
SA20067170,현대커머셜 클라우데라 라이선스 재계약(8노드),25,"14,000,000",NaN,nan,nan
SA19064715,현대캐피탈 클라우데라 라이선스 도입(29노드) 및 증설(10노드),25,"89,500,000",NaN,nan,nan
BDA19145,심텍 SAS 도입 건_라이선스_구축,100,"30,772,187",심텍 서버 사내 이체,100,0
BDA19145,심텍 SAS 도입 건_라이선스_구축,100,"30,772,187",심텍 SAS 도입 건 라이센스 구축 인건비 이체 (한광일 대리),100,0
2000071707,롯데하이마트 SAS 라이선스(MA) 재계약,100,"34,600,000",롯데하이마트 SAS 라이선스(MA) 재계약,100,0
SA19064633,(주)문화방송 SAS 리뉴얼,100,"5,040,000",(주)문화방송 SAS 리뉴얼,100,0
SA19064647,보라매병원 SAS 라이선스 리뉴얼,100,"3,864,000",보라매병원 SAS 라이선스 리뉴얼,100,0
SA20067281,바이오스타랩 SAS 라이선스 재계약,100,"6,350,000",NaN,nan,nan
SA19064666,LG화학 SAS 리뉴얼_2020,100,"349,658,500",LG화학 SAS 리뉴얼_2020,100,"4,658,500"
SA19065364,대림산업 Oracle EPM &재무전망 유지보수_2020,100,"847,000",NaN,nan,nan
SA19066293,한국신용정보원 SAS 라이선스 재계약,100,"108,400,000",NaN,nan,nan
2000072610,2020년 아카데미 재계약,100,0,2020년 아카데미 재계약,100,"29,470,000"
SA19063832,아카데미 재계약(2020년1월)고려대학교 외 1건,100,"11,350,000",NaN,nan,nan
BNA19166,환국환경정책연구원 AWS 디파짓 계약,0,0,환국환경정책연구원 AWS 디파짓 계약,100,"503,600"
SA19064680,SAS 소프트웨어 재계약,100,0,NaN,nan,nan
SA19065756,인천국제공항공사 빅데이터 라이선스 판매,50,0,NaN,nan,nan
SA20067189,2019년 코오롱 그룹 IT 인프라 서비스 전산 용역_계약전,100,"20,496,415",2019년 코오롱 그룹 IT 인프라 서비스 전산 용역_계약전,100,"20,796,415"
BDA19154,데이터분석 인프라 시스템 구축 사업,100,"105,831,235",데이터분석 인프라 시스템 구축 사업 품질비용 내부이체(빅데이터사업팀 -> QA팀),100,0
BDA19154,데이터분석 인프라 시스템 구축 사업,100,"105,831,235",데이터분석 인프라 시스템 구축 사업,100,"165,768,295"
2000071509,SAS소프트웨어 및 포지션평가솔루션 재계약,100,"60,000,000",SAS소프트웨어 및 포지션평가솔루션 재계약,100,0
SA19062212,전사 빅데이터 플랫폼 구축사업,0,0,NaN,nan,nan
SA20066873,CDH하둡 플랫폼 재계약,75,0,NaN,nan,nan
SA20066830,호튼웍스 Subscription 도입,50,0,NaN,nan,nan
SA20067180,CDH 하둡 플랫폼 재계약,100,"20,928,000",NaN,nan,nan
2000073220,NaN,nan,nan,한국공항공사 클라우데라 라이선스 공급(8노드),100,0
2000073218,NaN,nan,nan,하나은행 '20년 HDP 재계약-5SKU,100,0
2000073143,NaN,nan,nan,농협은행 '20년 HDP 재계약-2SKU,100,0
2000073051,NaN,nan,nan,하나카드 '20년 HDP 재계약-5SKU,100,"122,000,000"
SA20067818,NaN,nan,nan,현대카드.캐피탈 클라우데라 신규 노드 도입(24노드),100,0
2000072860,NaN,nan,nan,바이오스타랩 SAS 라이선스 재계약,100,"6,350,000"
BNA20031,NaN,nan,nan,국도화학 연결시스템 유지보수_2020,100,"1,016,400"
BDA20003,NaN,nan,nan,대림산업 Oracle EPM &재무전망 유지보수_2020,100,"931,700"
2000073024,NaN,nan,nan,한국신용정보원 SAS 라이선스 재계약,100,"108,401,000"
SA20067746,NaN,nan,nan,아난티 연결시스템 구축,0,0
BKA20008,NaN,nan,nan,경영학과 2020년도 아카데미 재계약,100,"1,846,667"
BKA20006,NaN,nan,nan,(사회의학교실)2020년도 아카데미 재계약,100,"7,095,000"
2000073094,NaN,nan,nan,(교양학과) 2020년 아카데미 재계약,100,0
2000072984,NaN,nan,nan,(서울행정) 아카데미 재계약,100,"9,250,000"
2000073097,NaN,nan,nan,SAS 소프트웨어 재계약,100,0
SA20067586,NaN,nan,nan,관세청 빅데이터플랫폼 구축,0,0
2000073062,NaN,nan,nan,CDH 하둡 플랫폼 재계약,100,"21,000,000"
SA20067590,NaN,nan,nan,DW Offloading을 위한 PoC 수행,25,0
SA20067644,NaN,nan,nan,분석 플랫폼 시스템 구축 사업,0,0

In [15]:
#boss_rate_ch = df_outer.query('GP1_1_x.isnull() and GP1_1_x != GP1_1_y', engine='python')
boss_rate_ch = df_outer.query('GP1_1_x.notnull() and GP1_1_y.notnull() and GP1_1_x != GP1_1_y', engine='python')
#boss_rate_ch = df_outer[df_outer['GP1_1_x'] != df_outer['GP1_1_y']]
boss_rate_ch.loc[:,['PJT명_x','구분_x','확률_x','GP1_1_x','GP1_2_x','PJT명_y','구분_y','확률_y','GP1_1_y','GP1_2_y']]

,PJT명_x,구분_x,확률_x,GP1_1_x,GP1_2_x,PJT명_y,구분_y,확률_y,GP1_1_y,GP1_2_y
PJT코드,,,,,,,,,,
BDA19140,신한AI 인프라 고도화 구축사업,G,100,"49,307,250","46,106,406",신한AI 인프라 고도화 구축사업 수행,사내,100,"-14,300,000",0
BDA19140,신한AI 인프라 고도화 구축사업,G,100,"49,307,250","46,106,406",신한AI 인프라 고도화 구축사업 품질비용 내부이체(빅데이터사업팀 -> QA팀),사내,100,"-1,170,000","-1,170,000"
BDA19140,신한AI 인프라 고도화 구축사업,G,100,"49,307,250","46,106,406",신한AI 인프라 고도화 구축사업 인건비 이체 (한수정 대리),사내,100,"-8,700,000",0
2000071996,현대커머셜 '20년 SAS 라이선스 재계약,G,100,"-114,000",0,현대커머셜 '20년 SAS 라이선스 재계약,G,0,0,0
SA19066494,이베이코리아 클라우데라 S/W 도입,H,100,"1,800,000",0,이베이코리아 클라우데라 S/W 도입,H,100,0,0
BDA19145,심텍 SAS 도입 건_라이선스_구축,G,100,"26,867,001","25,138,250",심텍 서버 사내 이체,사내,100,"-3,500,000",0
BDA19145,심텍 SAS 도입 건_라이선스_구축,G,100,"26,867,001","25,138,250",심텍 SAS 도입 건 라이센스 구축 인건비 이체 (한광일 대리),사내,100,"-8,700,000","-8,700,000"
2000071707,롯데하이마트 SAS 라이선스(MA) 재계약,G,100,"1,000",0,롯데하이마트 SAS 라이선스(MA) 재계약,G,100,0,"1,000"
SA19064633,(주)문화방송 SAS 리뉴얼,H,100,"652,000",0,(주)문화방송 SAS 리뉴얼,H,100,0,"680,000"
SA19064647,보라매병원 SAS 라이선스 리뉴얼,H,100,"394,800",0,보라매병원 SAS 라이선스 리뉴얼,H,100,0,"394,800"
SA19064666,LG화학 SAS 리뉴얼_2020,H,100,"50,423,500","396,000",LG화학 SAS 리뉴얼_2020,H,100,"423,500","50,396,000"
2000072610,2020년 아카데미 재계약,G,100,0,"2,210,000",2020년 아카데미 재계약,G,100,"2,210,000",0
BNA19166,환국환경정책연구원 AWS 디파짓 계약,G,0,0,0,환국환경정책연구원 AWS 디파짓 계약,G,100,"346,350","11,880"
SA19056837,빅데이터사업팀_사내거래,H,100,"-30,456,770","-20,855,000",빅데이터사업팀_사내거래,H,100,-1,"-12,155,000"
SA20067189,2019년 코오롱 그룹 IT 인프라 서비스 전산 용역_계약전,H,100,"20,496,415","20,496,415",2019년 코오롱 그룹 IT 인프라 서비스 전산 용역_계약전,H,100,"20,796,415","20,796,415"
BDA19154,데이터분석 인프라 시스템 구축 사업,G,100,"62,264,647","58,293,438",데이터분석 인프라 시스템 구축 사업 품질비용 내부이체(빅데이터사업팀 -> QA팀),사내,100,"-2,332,185","-2,332,185"
BDA19154,데이터분석 인프라 시스템 구축 사업,G,100,"62,264,647","58,293,438",데이터분석 인프라 시스템 구축 사업,G,100,"65,801,707","67,539,902"
2000071509,SAS소프트웨어 및 포지션평가솔루션 재계약,G,100,"3,000,000",0,SAS소프트웨어 및 포지션평가솔루션 재계약,G,100,0,0

In [69]:
# 팀분기합계 컬럼 생성
pd.options.display.float_format = '{:,.0f}'.format
boss_this_sum = boss_sales.groupby(['집계'])['매출_1','GP1_1','매출_2','GP1_2','매출_3','GP1_3','매출_4','GP1_4','매출_5','GP1_5','매출_6','GP1_6'].sum()/1000
boss_this_sum['매출_Q1'] = boss_this_sum['매출_1'] + boss_this_sum['매출_2'] + boss_this_sum['매출_3']  
boss_this_sum['GP1_Q1'] = boss_this_sum['GP1_1'] + boss_this_sum['GP1_2'] + boss_this_sum['GP1_3']  
boss_this_sum['매출_Q2'] = boss_this_sum['매출_4'] + boss_this_sum['매출_5'] + boss_this_sum['매출_6']  
boss_this_sum['GP1_Q2'] = boss_this_sum['GP1_4'] + boss_this_sum['GP1_5'] + boss_this_sum['GP1_6']  
boss_this_sum.loc[:,:]
format_dict = {'매출_1': '{:,.0f}', 'GP1_1': '{:,.0f}', '매출_2': '{:,.0f}', 'GP1_2': '{:,.0f}', '매출_3': '{:,.0f}', 'GP1_3': '{:,.0f}', '매출_4': '{:,.0f}', 'GP1_4': '{:,.0f}',
               '매출_5': '{:,.0f}', 'GP1_5': '{:,.0f}', '매출_6': '{:,.0f}', 'GP1_6': '{:,.0f}', '매출_Q1': '{:,.0f}', 'GP1_Q1': '{:,.0f}', '매출_Q2': '{:,.0f}', 'GP1_Q2': '{:,.0f}'}
boss_this_sum.style.format(format_dict)

In [68]:
# 팀분기합계 컬럼 생성
boss_this_sum = boss_sales.groupby(['영업대표','집계'])['매출_1','GP1_1','매출_2','GP1_2','매출_3','GP1_3','매출_4','GP1_4','매출_5','GP1_5','매출_6','GP1_6'].sum()/1000
boss_this_sum['매출_Q1'] = boss_this_sum['매출_1'] + boss_this_sum['매출_2'] + boss_this_sum['매출_3']  
boss_this_sum['GP1_Q1'] = boss_this_sum['GP1_1'] + boss_this_sum['GP1_2'] + boss_this_sum['GP1_3']  
boss_this_sum['매출_Q2'] = boss_this_sum['매출_4'] + boss_this_sum['매출_5'] + boss_this_sum['매출_6']  
boss_this_sum['GP1_Q2'] = boss_this_sum['GP1_4'] + boss_this_sum['GP1_5'] + boss_this_sum['GP1_6']  
boss_this_sum.to_csv(result_filepath + 'boss_salesman.csv', encoding='euc-kr')
boss_this_sum

format_dict = {'매출_1': '{:,.0f}', 'GP1_1': '{:,.0f}', '매출_2': '{:,.0f}', 'GP1_2': '{:,.0f}', '매출_3': '{:,.0f}', 'GP1_3': '{:,.0f}', '매출_4': '{:,.0f}', 'GP1_4': '{:,.0f}',
               '매출_5': '{:,.0f}', 'GP1_5': '{:,.0f}', '매출_6': '{:,.0f}', 'GP1_6': '{:,.0f}', '매출_Q1': '{:,.0f}', 'GP1_Q1': '{:,.0f}', '매출_Q2': '{:,.0f}', 'GP1_Q2': '{:,.0f}'}
boss_this_sum.style.format(format_dict)

In [75]:
# 확률별 컬럼 생성
boss_this_sum = boss_this.groupby(['확률','집계'])['매출_1','GP1_1','매출_2','GP1_2','매출_3','GP1_3','매출_4','GP1_4','매출_5','GP1_5','매출_6','GP1_6'].sum()/1000
boss_this_sum['매출_Q1'] = boss_this_sum['매출_1'] + boss_this_sum['매출_2'] + boss_this_sum['매출_3']  
boss_this_sum['GP1_Q1'] = boss_this_sum['GP1_1'] + boss_this_sum['GP1_2'] + boss_this_sum['GP1_3']  
boss_this_sum['매출_Q2'] = boss_this_sum['매출_4'] + boss_this_sum['매출_5'] + boss_this_sum['매출_6']  
boss_this_sum['GP1_Q2'] = boss_this_sum['GP1_4'] + boss_this_sum['GP1_5'] + boss_this_sum['GP1_6']  

boss_this_sum

format_dict = {'매출_1': '{:,.0f}', 'GP1_1': '{:,.0f}', '매출_2': '{:,.0f}', 'GP1_2': '{:,.0f}', '매출_3': '{:,.0f}', 'GP1_3': '{:,.0f}', '매출_4': '{:,.0f}', 'GP1_4': '{:,.0f}',
               '매출_5': '{:,.0f}', 'GP1_5': '{:,.0f}', '매출_6': '{:,.0f}', 'GP1_6': '{:,.0f}', '매출_Q1': '{:,.0f}', 'GP1_Q1': '{:,.0f}', '매출_Q2': '{:,.0f}', 'GP1_Q2': '{:,.0f}'}
boss_this_sum.style.format(format_dict)

In [76]:
# 구분별 컬럼 생성
boss_this_sum = boss_this.groupby(['구분','집계'])['매출_1','GP1_1','매출_2','GP1_2','매출_3','GP1_3','매출_4','GP1_4','매출_5','GP1_5','매출_6','GP1_6'].sum()/1000
boss_this_sum['매출_Q1'] = boss_this_sum['매출_1'] + boss_this_sum['매출_2'] + boss_this_sum['매출_3']  
boss_this_sum['GP1_Q1'] = boss_this_sum['GP1_1'] + boss_this_sum['GP1_2'] + boss_this_sum['GP1_3']  
boss_this_sum['매출_Q2'] = boss_this_sum['매출_4'] + boss_this_sum['매출_5'] + boss_this_sum['매출_6']  
boss_this_sum['GP1_Q2'] = boss_this_sum['GP1_4'] + boss_this_sum['GP1_5'] + boss_this_sum['GP1_6']  
boss_this_sum

format_dict = {'매출_1': '{:,.0f}', 'GP1_1': '{:,.0f}', '매출_2': '{:,.0f}', 'GP1_2': '{:,.0f}', '매출_3': '{:,.0f}', 'GP1_3': '{:,.0f}', '매출_4': '{:,.0f}', 'GP1_4': '{:,.0f}',
               '매출_5': '{:,.0f}', 'GP1_5': '{:,.0f}', '매출_6': '{:,.0f}', 'GP1_6': '{:,.0f}', '매출_Q1': '{:,.0f}', 'GP1_Q1': '{:,.0f}', '매출_Q2': '{:,.0f}', 'GP1_Q2': '{:,.0f}'}
boss_this_sum.style.format(format_dict)

In [ ]:
# 팀분기합계 컬럼 생성
boss_this_sum = boss_sales.(lambda x: x['period'], x['b'], x['N']), axis=1).groupby(['영업대표','period'])['매출_1','GP1_1','매출_2','GP1_2','매출_3','GP1_3','매출_4','GP1_4','매출_5','GP1_5','매출_6','GP1_6'].sum()
boss_this_sum['매출_Q1'] = boss_this_sum['매출_1'] + boss_this_sum['매출_2'] + boss_this_sum['매출_3']  
boss_this_sum['GP1_Q1'] = boss_this_sum['GP1_1'] + boss_this_sum['GP1_2'] + boss_this_sum['GP1_3']  
boss_this_sum['매출_Q2'] = boss_this_sum['매출_4'] + boss_this_sum['매출_5'] + boss_this_sum['매출_6']  
boss_this_sum['GP1_Q2'] = boss_this_sum['GP1_4'] + boss_this_sum['GP1_5'] + boss_this_sum['GP1_6']  
boss_this_sum.append
boss_this_sum